name: Run Automation Tests

on:
  push:
    branches:
      - dev
      - qa
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - staging

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run automation tests with HTML reporter
        run: npx playwright test --reporter=html
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        continue-on-error: true  # so that reports still generate even if tests fail

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
